apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myapp
  labels: {app: myapp}
spec:
  replicas: 1
  template:
    metadata: {labels: {app: myapp}}
    spec:
      containers:
      - name: myapp
        image: {DOCKER_SERVER}/go-http-server/myapp:latest
        command:
        ports:
          - containerPort: 8080
      imagePullSecrets:
      - name: regcred          
---
kind: Service
apiVersion: v1
metadata:
  name: myapp
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080          